In [5]:
import numpy as np

In [29]:
list = [[2,24,3493,39,39],[3,45,343,33,3]]
my_array = np.linspace(10,2,20,retstep=True)
my_array

(array([10.        ,  9.57894737,  9.15789474,  8.73684211,  8.31578947,
         7.89473684,  7.47368421,  7.05263158,  6.63157895,  6.21052632,
         5.78947368,  5.36842105,  4.94736842,  4.52631579,  4.10526316,
         3.68421053,  3.26315789,  2.84210526,  2.42105263,  2.        ]),
 np.float64(-0.42105263157894735))

In [47]:
x = np.arange(0,16)
x.reshape(2,2,4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [52]:
np.random.rand(10,2,)

array([[0.59809589, 0.22899489],
       [0.23248321, 0.40702133],
       [0.85997453, 0.12179761],
       [0.54112057, 0.84027719],
       [0.7295787 , 0.62360719],
       [0.30732636, 0.20974867],
       [0.81984256, 0.3665058 ],
       [0.63355676, 0.95783744],
       [0.58075805, 0.80175688],
       [0.88557012, 0.60122822]])

In [77]:
np.random.randint(2,34,20).reshape(4,5)
arrayint = np.random.randint(low=10,high=400,size=[4,5])
arrayint

array([[272, 365, 237,  21, 262],
       [248, 309, 206, 155,  29],
       [300, 204,  16, 354, 207],
       [171, 261, 237,  18, 311]], dtype=int32)

In [71]:
arrayint.max()

np.int32(394)

In [73]:
arrayint.mean()
np.median(arrayint)

np.float64(242.0)

In [81]:
arrayint

array([[272, 365, 237,  21, 262],
       [248, 309, 206, 155,  29],
       [300, 204,  16, 354, 207],
       [171, 261, 237,  18, 311]], dtype=int32)

In [87]:
arrayint[2][0:2]

array([300, 204], dtype=int32)